# Generated by Django 5.2.3 on 2026-05-11 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_preferee', models.CharField(blank=True, max_length=100)),
                ('historique_recherche', models.TextField(blank=True, help_text='Une recherche par ligne.')),
            ],
            options={
                'ordering': ['utilisateur__nom', 'utilisateur__prenom'],
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carte_etudiant', models.FileField(blank=True, null=True, upload_to='cartes_etudiants/')),
                ('carte_verifiee', models.BooleanField(default=False)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('competences', models.ManyToManyField(blank=True, related_name='prestataires', to='marketplace.competence')),
            ],
            options={
                'ordering': ['utilisateur__nom', 'utilisateur__prenom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('categorie', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_livraison', models.PositiveIntegerField(help_text='Délai en jours.')),
                ('avis', models.TextField(blank=True)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paiement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marketplace.prestataire')),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(default=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('consommateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='marketplace.consommateur')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='marketplace.service')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('consommateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='marketplace.consommateur')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='marketplace.service')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('CONSOMMATEUR', 'Consommateur'), ('PRESTATAIRE', 'Prestataire')], max_length=20)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to='marketplace.compte')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('biographie', models.TextField(blank=True)),
                ('note_moyenne', models.FloatField(default=0)),
                ('score_reputation', models.FloatField(default=0)),
                ('nb_commandes_total', models.PositiveIntegerField(default=0)),
                ('universite', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='marketplace.utilisateur')),
            ],
            options={
                'ordering': ['utilisateur__nom', 'utilisateur__prenom'],
            },
        ),
        migrations.AddField(
            model_name='prestataire',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire', to='marketplace.utilisateur'),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='marketplace.service')),
                ('utilisateurs', models.ManyToManyField(related_name='discussions', to='marketplace.utilisateur')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='consommateur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consommateur', to='marketplace.utilisateur'),
        ),
    ]
