# Generated by Django 5.2.3 on 2026-06-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('taux_completion', models.FloatField(default=0.0)),
                ('score_global', models.FloatField(default=0.0)),
                ('nb_avis', models.PositiveIntegerField(default=0)),
                ('nb_commandes_total', models.PositiveIntegerField(default=0)),
                ('badge_confiance', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prestataire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to='marketplace.prestataire')),
            ],
            options={
                'ordering': ['-score_global'],
            },
        ),
    ]
