# Generated by Django 5.2.3 on 2026-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_reputationscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
